### ISSUE TITLE
Working yet?!

### ISSUE THREAD

**Issue by galbraithmedia1** [kylebaugh/intimacy-tracker#1]
Cool idea

**Comment by andrewse02** [comment]
I need this **_desperately_...**

**Comment by galbraithmedia1** [comment]
Same. I would love to contribute to this project. Is it open source?

**Comment by andrewse02** [comment]
Not sure, I can't tell.

**Comment by galbraithmedia1** [comment]
Mmm.... I wonder if the project owner has any intimate experience.
